//Function to update Methods inside the views
function changemembersvisibility()
{
var numberofteammembers = document.getElementById("numberofteammembers");
if(numberofteammembers.value == "1")
{

document.getElementById("teammember1firstnamelabel").style.visibility="visible";
document.getElementById("teammember1firstname").style.visibility="visible";
document.getElementById("teammember1surnamelabel").style.visibility="visible";
document.getElementById("teammember1surname").style.visibility="visible";
document.getElementById("teammember2firstnamelabel").style.visibility="hidden";
document.getElementById("teammember2firstname").style.visibility="hidden";
document.getElementById("teammember2surnamelabel").style.visibility="hidden";
document.getElementById("teammember2surname").style.visibility="hidden";
document.getElementById("teammember3firstnamelabel").style.visibility="hidden";
document.getElementById("teammember3firstname").style.visibility="hidden";
document.getElementById("teammember3surnamelabel").style.visibility="hidden";
document.getElementById("teammember3surname").style.visibility="hidden";
document.getElementById("teammember4firstnamelabel").style.visibility="hidden";
document.getElementById("teammember4firstname").style.visibility="hidden";
document.getElementById("teammember4surnamelabel").style.visibility="hidden";
document.getElementById("teammember4surname").style.visibility="hidden";
document.getElementById("teammember5firstnamelabel").style.visibility="hidden";
document.getElementById("teammember5firstname").style.visibility="hidden";
document.getElementById("teammember5surnamelabel").style.visibility="hidden";
document.getElementById("teammember5surname").style.visibility="hidden";
document.getElementById("teammember6firstnamelabel").style.visibility="hidden";
document.getElementById("teammember6firstname").style.visibility="hidden";
document.getElementById("teammember6surnamelabel").style.visibility="hidden";
document.getElementById("teammember6surname").style.visibility="hidden";
document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
document.getElementById("teammember7firstname").style.visibility="hidden";
document.getElementById("teammember7surnamelabel").style.visibility="hidden";
document.getElementById("teammember7surname").style.visibility="hidden";
document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
document.getElementById("teammember8firstname").style.visibility="hidden";
document.getElementById("teammember8surnamelabel").style.visibility="hidden";
document.getElementById("teammember8surname").style.visibility="hidden";

}
if(numberofteammembers.value == "2")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember3firstname").style.visibility="hidden";
  document.getElementById("teammember3surnamelabel").style.visibility="hidden";
  document.getElementById("teammember3surname").style.visibility="hidden";
  document.getElementById("teammember4firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember4firstname").style.visibility="hidden";
  document.getElementById("teammember4surnamelabel").style.visibility="hidden";
  document.getElementById("teammember4surname").style.visibility="hidden";
  document.getElementById("teammember5firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember5firstname").style.visibility="hidden";
  document.getElementById("teammember5surnamelabel").style.visibility="hidden";
  document.getElementById("teammember5surname").style.visibility="hidden";
  document.getElementById("teammember6firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember6firstname").style.visibility="hidden";
  document.getElementById("teammember6surnamelabel").style.visibility="hidden";
  document.getElementById("teammember6surname").style.visibility="hidden";
  document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember7firstname").style.visibility="hidden";
  document.getElementById("teammember7surnamelabel").style.visibility="hidden";
  document.getElementById("teammember7surname").style.visibility="hidden";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "3")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember4firstname").style.visibility="hidden";
  document.getElementById("teammember4surnamelabel").style.visibility="hidden";
  document.getElementById("teammember4surname").style.visibility="hidden";
  document.getElementById("teammember5firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember5firstname").style.visibility="hidden";
  document.getElementById("teammember5surnamelabel").style.visibility="hidden";
  document.getElementById("teammember5surname").style.visibility="hidden";
  document.getElementById("teammember6firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember6firstname").style.visibility="hidden";
  document.getElementById("teammember6surnamelabel").style.visibility="hidden";
  document.getElementById("teammember6surname").style.visibility="hidden";
  document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember7firstname").style.visibility="hidden";
  document.getElementById("teammember7surnamelabel").style.visibility="hidden";
  document.getElementById("teammember7surname").style.visibility="hidden";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "4")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="visible";
  document.getElementById("teammember4firstname").style.visibility="visible";
  document.getElementById("teammember4surnamelabel").style.visibility="visible";
  document.getElementById("teammember4surname").style.visibility="visible";
  document.getElementById("teammember5firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember5firstname").style.visibility="hidden";
  document.getElementById("teammember5surnamelabel").style.visibility="hidden";
  document.getElementById("teammember5surname").style.visibility="hidden";
  document.getElementById("teammember6firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember6firstname").style.visibility="hidden";
  document.getElementById("teammember6surnamelabel").style.visibility="hidden";
  document.getElementById("teammember6surname").style.visibility="hidden";
  document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember7firstname").style.visibility="hidden";
  document.getElementById("teammember7surnamelabel").style.visibility="hidden";
  document.getElementById("teammember7surname").style.visibility="hidden";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "5")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="visible";
  document.getElementById("teammember4firstname").style.visibility="visible";
  document.getElementById("teammember4surnamelabel").style.visibility="visible";
  document.getElementById("teammember4surname").style.visibility="visible";
  document.getElementById("teammember5firstnamelabel").style.visibility="visible";
  document.getElementById("teammember5firstname").style.visibility="visible";
  document.getElementById("teammember5surnamelabel").style.visibility="visible";
  document.getElementById("teammember5surname").style.visibility="visible";
  document.getElementById("teammember6firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember6firstname").style.visibility="hidden";
  document.getElementById("teammember6surnamelabel").style.visibility="hidden";
  document.getElementById("teammember6surname").style.visibility="hidden";
  document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember7firstname").style.visibility="hidden";
  document.getElementById("teammember7surnamelabel").style.visibility="hidden";
  document.getElementById("teammember7surname").style.visibility="hidden";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "6")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="visible";
  document.getElementById("teammember4firstname").style.visibility="visible";
  document.getElementById("teammember4surnamelabel").style.visibility="visible";
  document.getElementById("teammember4surname").style.visibility="visible";
  document.getElementById("teammember5firstnamelabel").style.visibility="visible";
  document.getElementById("teammember5firstname").style.visibility="visible";
  document.getElementById("teammember5surnamelabel").style.visibility="visible";
  document.getElementById("teammember5surname").style.visibility="visible";
  document.getElementById("teammember6firstnamelabel").style.visibility="visible";
  document.getElementById("teammember6firstname").style.visibility="visible";
  document.getElementById("teammember6surnamelabel").style.visibility="visible";
  document.getElementById("teammember6surname").style.visibility="visible";
  document.getElementById("teammember7firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember7firstname").style.visibility="hidden";
  document.getElementById("teammember7surnamelabel").style.visibility="hidden";
  document.getElementById("teammember7surname").style.visibility="hidden";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "7")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="visible";
  document.getElementById("teammember4firstname").style.visibility="visible";
  document.getElementById("teammember4surnamelabel").style.visibility="visible";
  document.getElementById("teammember4surname").style.visibility="visible";
  document.getElementById("teammember5firstnamelabel").style.visibility="visible";
  document.getElementById("teammember5firstname").style.visibility="visible";
  document.getElementById("teammember5surnamelabel").style.visibility="visible";
  document.getElementById("teammember5surname").style.visibility="visible";
  document.getElementById("teammember6firstnamelabel").style.visibility="visible";
  document.getElementById("teammember6firstname").style.visibility="visible";
  document.getElementById("teammember6surnamelabel").style.visibility="visible";
  document.getElementById("teammember6surname").style.visibility="visible";
  document.getElementById("teammember7firstnamelabel").style.visibility="visible";
  document.getElementById("teammember7firstname").style.visibility="visible";
  document.getElementById("teammember7surnamelabel").style.visibility="visible";
  document.getElementById("teammember7surname").style.visibility="visible";
  document.getElementById("teammember8firstnamelabel").style.visibility="hidden";
  document.getElementById("teammember8firstname").style.visibility="hidden";
  document.getElementById("teammember8surnamelabel").style.visibility="hidden";
  document.getElementById("teammember8surname").style.visibility="hidden";


}
if(numberofteammembers.value == "8")
{
  document.getElementById("teammember1firstnamelabel").style.visibility="visible";
  document.getElementById("teammember1firstname").style.visibility="visible";
  document.getElementById("teammember1surnamelabel").style.visibility="visible";
  document.getElementById("teammember1surname").style.visibility="visible";
  document.getElementById("teammember2firstnamelabel").style.visibility="visible";
  document.getElementById("teammember2firstname").style.visibility="visible";
  document.getElementById("teammember2surnamelabel").style.visibility="visible";
  document.getElementById("teammember2surname").style.visibility="visible";
  document.getElementById("teammember3firstnamelabel").style.visibility="visible";
  document.getElementById("teammember3firstname").style.visibility="visible";
  document.getElementById("teammember3surnamelabel").style.visibility="visible";
  document.getElementById("teammember3surname").style.visibility="visible";
  document.getElementById("teammember4firstnamelabel").style.visibility="visible";
  document.getElementById("teammember4firstname").style.visibility="visible";
  document.getElementById("teammember4surnamelabel").style.visibility="visible";
  document.getElementById("teammember4surname").style.visibility="visible";
  document.getElementById("teammember5firstnamelabel").style.visibility="visible";
  document.getElementById("teammember5firstname").style.visibility="visible";
  document.getElementById("teammember5surnamelabel").style.visibility="visible";
  document.getElementById("teammember5surname").style.visibility="visible";
  document.getElementById("teammember6firstnamelabel").style.visibility="visible";
  document.getElementById("teammember6firstname").style.visibility="visible";
  document.getElementById("teammember6surnamelabel").style.visibility="visible";
  document.getElementById("teammember6surname").style.visibility="visible";
  document.getElementById("teammember7firstnamelabel").style.visibility="visible";
  document.getElementById("teammember7firstname").style.visibility="visible";
  document.getElementById("teammember7surnamelabel").style.visibility="visible";
  document.getElementById("teammember7surname").style.visibility="visible";
  document.getElementById("teammember8firstnamelabel").style.visibility="visible";
  document.getElementById("teammember8firstname").style.visibility="visible";
  document.getElementById("teammember8surnamelabel").style.visibility="visible";
  document.getElementById("teammember8surname").style.visibility="visible";


}

}
